#!/usr/bin/env python3
"""
VibeTipp – First-Run Setup Script
Run once after cloning: python setup.py
"""
import os
import sys
import secrets
import shutil
import getpass
from pathlib import Path

ROOT = Path(__file__).parent


def generate_secret_key() -> str:
    return secrets.token_hex(32)


def create_env(port: int, secret_key: str, data_dir: str = "data") -> None:
    env_path = ROOT / ".env"
    content = f"""# VibeTipp configuration – generated by setup.py
SECRET_KEY={secret_key}
PORT={port}
DATA_DIR={data_dir}
SESSION_LIFETIME_HOURS=24
MAX_UPLOAD_SIZE_MB=1
MAX_GOALS=30
LOGIN_MAX_ATTEMPTS=10
LOGIN_LOCKOUT_MINUTES=15
"""
    env_path.write_text(content, encoding="utf-8")
    print(f"  Created .env  (port={port})")


def ensure_data_dir(data_dir: str) -> Path:
    p = ROOT / data_dir
    p.mkdir(parents=True, exist_ok=True)
    src = ROOT / "data" / "matches.csv"
    dst = p / "matches.csv"
    if src.exists() and not dst.exists():
        shutil.copy(src, dst)
        print(f"  Copied matches.csv → {data_dir}/matches.csv")
    return p


def create_admin_user(data_dir: Path, username: str, password: str, display: str) -> None:
    sys.path.insert(0, str(ROOT))
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env")
    from app.auth.hashing import hash_password
    from app.repositories.users import UserRepository, HEADERS

    repo = UserRepository(data_dir)
    if repo.find_by_username(username):
        print(f"  User '{username}' already exists – skipping.")
        return

    repo.save({
        "username": username,
        "password_hash": hash_password(password),
        "role": "admin",
        "display_name": display,
        "active": True,
        "paid": False,
    })
    print(f"  Admin user '{username}' created.")


def main():
    print("=" * 55)
    print("  VibeTipp – Setup")
    print("=" * 55)

    # ── Port ────────────────────────────────────────────────────
    port_input = input("\nPort [8081]: ").strip()
    port = int(port_input) if port_input.isdigit() else 8081

    # ── Secret key ──────────────────────────────────────────────
    env_path = ROOT / ".env"
    if env_path.exists():
        overwrite = input("\n.env already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("  Keeping existing .env")
        else:
            create_env(port, generate_secret_key())
    else:
        create_env(port, generate_secret_key())

    # ── Data directory ──────────────────────────────────────────
    data_dir_input = input("\nData directory [data]: ").strip()
    data_dir_str = data_dir_input if data_dir_input else "data"
    data_path = ensure_data_dir(data_dir_str)

    # ── Admin account ───────────────────────────────────────────
    print(f"\nAdmin account setup")
    print("  Default: username=admin  password=admin1234")
    custom = input("  Use custom credentials? [y/N]: ").strip().lower()

    if custom == "y":
        username = input("  Admin username [admin]: ").strip() or "admin"
        display  = input("  Display name   [Admin]: ").strip() or "Admin"
        while True:
            pw = getpass.getpass("  Password (min 8 chars): ")
            if len(pw) >= 8:
                break
            print("  Password too short!")
    else:
        username = "admin"
        display  = "Admin"
        pw       = "admin1234"
        print("  Using default credentials: admin / admin1234")

    try:
        create_admin_user(data_path, username, pw, display)
    except Exception as e:
        print(f"  WARNING: Could not create user – {e}")
        print("  You can create an admin manually: python scripts/create_user.py")

    # ── Done ────────────────────────────────────────────────────
    print("\n" + "=" * 55)
    print(f"  Setup complete!")
    print(f"  Start: python main.py")
    print(f"  Open:  http://localhost:{port}")
    print(f"  Login: {username} / {'(your password)' if custom == 'y' else 'admin1234'}")
    if pw == "admin1234":
        print("\n  *** Change the default password after first login! ***")
    print("=" * 55)


if __name__ == "__main__":
    main()
